### ISSUE TITLE
Add configuration options for hashing of email address and inclusion of name

### ISSUE THREAD

**Issue by JoelDSmith** [central-queensland-uni/moodle-logstore_xapi#2]
We've currently hard-coded the email address to always be hashed when recording logs. This should be behind a configuration option. 

I've also noticed that we've removed the logging of the user's name as part of the customisations. This should be behind a configuration option as well.

- [ ] Configuration option for hashing email address
- [ ] Configuration option for including name

**Comment by JoelDSmith** [comment]
@gvm-dev Looks like I can't assign this to you until you comment here. 😕

**Comment by gvm-dev** [comment]
Roger that - will look at this next week.

**Comment by JoelDSmith** [comment]
This was resolved by #3; closing...
